apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.storeName }}-ingress
  namespace: store-{{ .Values.storeName }}
  labels:
    app: wordpress
    store: {{ .Values.storeName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.storeDomain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.storeName }}-wordpress
                port:
                  number: 80
