apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.storeName }}-mariadb
  namespace: store-{{ .Values.storeName }}
  labels:
    app: mariadb
    store: {{ .Values.storeName }}
spec:
  type: ClusterIP
  ports:
    - port: 3306
      targetPort: mysql
      protocol: TCP
      name: mysql
  selector:
    app: mariadb
    store: {{ .Values.storeName }}
