apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-mariadb-data
  namespace: store-{{ .Values.storeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mariadb.storage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storeName }}-wordpress-data
  namespace: store-{{ .Values.storeName }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.wordpress.storage }}
