apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeName }}-db-secret
  namespace: store-{{ .Values.storeName }}
type: Opaque
data:
  root-password: {{ .Values.mariadb.rootPassword | b64enc }}
  password: {{ .Values.mariadb.password | b64enc }}
  database: {{ .Values.mariadb.database | b64enc }}
  user: {{ .Values.mariadb.user | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.storeName }}-wp-secret
  namespace: store-{{ .Values.storeName }}
type: Opaque
data:
  admin-user: {{ .Values.wordpress.adminUser | b64enc }}
  admin-password: {{ .Values.wordpress.adminPassword | b64enc }}
  admin-email: {{ .Values.wordpress.adminEmail | b64enc }}
