backend:
  imagePullPolicy: Never
  env:
    BASE_DOMAIN: 127.0.0.1.nip.io
    STORE_PORT: "8082"

dashboard:
  imagePullPolicy: Never

ingress:
  className: nginx
  dashboardHost: dashboard.127.0.0.1.nip.io
  backendHost: api.127.0.0.1.nip.io
